# Generated by Django 3.0 on 2020-01-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_gym', '0003_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_gym.Instructor'),
        ),
    ]
