# Generated by Django 3.0 on 2020-01-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_gym', '0007_auto_20200125_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
    ]
